config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get 'dashboard', to: 'pages#dashboard', as: :dashboard

  resources :instruments do
    resources :bookings, only: [:create, :show, :index]
  end
  resources :bookings, only: [:destroy, :update]
end


# original routes
#   resources :instruments do
#     resources :bookings, only: [:create]
#   end
#   resources :bookings, only: [:index, :show, :destroy, :update]
# patch '/instruments/:instrument_id/bookings/:id', to: 'bookings#update', as: :update_booking

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :instrument
  belongs_to :user

  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/instrument.rb
class Instrument < ApplicationRecord
  belongs_to :user
  has_many :bookings

  validates :name, presence: true
  # change category names later
  validates :category, presence: true, acceptance: { accept: ["bowed strings", "wood wind", "brass", "percussions", "keyboard" , "guitar family"] }
  validates :description, presence: true
  has_one_attached :photo

  include PgSearch::Model
  pg_search_scope :search_by_name_and_category,
    against: [ :name, :category ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :instruments, through: :bookings
  has_many :bookings
  has_one_attached :photo

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true, uniqueness: true

  # validation for email uniqueness?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  # creating new booking for specific instrument with user params and saving it
  # rendering new page if user did not input all params
  def create
    @instrument = Instrument.find(params[:instrument_id])
    @booking = Booking.new(booking_params)
    @booking.instrument = @instrument
    @booking.user = current_user
    @booking.status = "Pending validation"
    # maybe stay on the page and disable the booking button and get a notifaction
    #or redirect to dashboard
    if @booking.save
      redirect_to dashboard_path
    else
      redirect_to instrument_path(@instrument)
    end
  end

  # def index
  #    @bookings = Booking.where(user_id: current_user.id)
  # end

  def update
    set_booking
    @booking.update(booking_params)
    @booking.save
    redirect_to dashboard_path
  end

  def destroy
    set_booking
    @booking.destroy
    redirect_to dashboard_path
  end

  private

  # whitelisting instrument params for input
  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :total_price, :status)
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController

  # Creating an instance of all instruments
  def index
    if params[:query].present?
      # sql_query = "name ILIKE :query OR category ILIKE :query"
      # @instruments = Instrument.where(sql_query, query: "%#{params[:query]}%")
      @instruments = Instrument.search_by_name_and_category(params[:query])
    else
      # @instruments = Instrument.all
      @instruments = Instrument.all
    end
  end

  # finding instrument user clicked on and creating inctance of booking for form
  def show
    @instrument = Instrument.find(params[:id])
    @booking = Booking.new
  end

  # creating new instance of instrument for instrument creation form
  def new
    @instrument = Instrument.new
    @category = ["bowed strings", "wood wind", "brass", "percussions", "keyboard" , "guitar family"]
  end

  # now actually creating the new instrument with user params and saving it
  # rendering new page if user did not input all params
  def create
    @instrument = Instrument.new(instrument_params)
    @instrument.user = current_user
    if @instrument.save
      redirect_to instrument_path(@instrument), notice: 'Created new instrument.'
    else
      render :new
    end
  end

  # finding instrument to destroy - destroying the instrument - redirecting to root_path
  def destroy
    @instrument = Instrument.find(params[:id])
    @instrument.destroy
    redirect_to root_path
  end

  # finding instrument to update - updating instrument with user_params - redirecting to instrument_path
  def update
    @instrument = Instrument.find(params[:id])
    @instrument.update(instrument_params)
    redirect_to instrument_path(@instrument)
  end

  # finding instrument to update and show it to the user
  # have to check if we need this method
  # def edit
  #  @instrument = Instrument.find(params[:id])
  # end

  private

  # whitelisting instrument params for input
  def instrument_params
    params.require(:instrument).permit(:name, :category, :description, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  # Searchbar needs instance of all instruments
  def home
    @instruments = Instrument.all
  end

  # User wants to see all his instruments and bookings
  # check what we need to include for device to work
  def dashboard
    @instruments = Instrument.where(user_id: current_user.id)
    @bookings = Booking.where(user_id: current_user.id)

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/instruments/_form.html.erb
<% <% f.input :photo, as: :file %>

app/views/instruments/index.html.erb
<div class="container banana">

  <h1>Found <%= @instruments.count %> Instruments</h1>

  <div class="row d-flex justify-content-start">

    <% @instruments.each do |instrument| %>

      <div class="card-trip col-md-auto">
        <% if instrument.photo.attached? %>
          <%= link_to (cl_image_tag instrument.photo.key, height: 320, width: 320, crop: :fill, class: 'instrument-image'), instrument_path(instrument) %>
        <% else %>
          <%= link_to instrument_path(instrument) do %>
            <%= image_tag '/app/assets/images/guitar_dummy.jpg', class: 'instrument-image' %>
          <% end %>
        <% end %>
        <div class="card-trip-infos">
          <div>
            <h2><%= instrument.name.titleize %></h2><%= link_to "Details", instrument %>
            <p><%= instrument.category.titleize %></p>

          </div>
          <h2 class="card-trip-pricing">5 🍺</h2>
          <%= cl_image_tag instrument.user.photo.key, height: 100, width: 100, crop: :fill, class: 'card-trip-user avatar-bordered'  %>
        </div>
      </div>

    <% end %>

  </div>

</div>

app/views/instruments/new.html.erb
<div class="container">
  <div class="instrument-form">
    <h1>Add a new instrument</h1>
    <br>
    <%= simple_form_for @instrument do |f| %>
    <%= f.input :name, placeholder: "Fender Stratocaster" %>
    <%= f.input :category, collection: @category %>
    <%= f.input :description, placeholder: "The one Jimi Hendrix played.." %>
    <label class="btn btn-ghost">Upload a picture!
      <span style="display:none;">
        <%= f.input :photo, as: :file, class: 'hidden' %>
      </span>
    </label>
    <label class="btn btn-solid">Add Instrument!
      <span style="display:none;">
        <%= f.submit "Add Instrument" %>
      </span>
    </label>
    <% end %>
    <br>

      <%= link_to 'Back to Homepage', root_path  %>

  </div>
</div>

app/views/instruments/show.html.erb
<div class="container">

  <div class="name-div">
    <h1><%= @instrument.name.titleize %></h1>
  </div>

  <div class="d-flex show-card">

    <div class="instrument-picture col-lg-6">
      <%= cl_image_tag @instrument.photo.key, height: 600, width: 600, crop: :fill, class: 'instrument-picture' %>
      <%= cl_image_tag @instrument.user.photo.key, height: 100, width: 100, crop: :fill, class: 'card-trip-user avatar-bordered'  %>
    </div>

    <div class="col-lg-6 show-card-details">
      <% if @instrument.user != current_user %>

      <div class="instrument-details">
        <h4>Description:</h4>
        <p><%= @instrument.description %></p>
      </div>

      <div class="container">

          <div class="row">
            <h4>Select dates:</h4>
            <div class="booking-form">
            <%= simple_form_for [@instrument, @booking] do |f| %>
              From: <%= f.text_field :start_date, class: "start_date", data: { behavior: "flatpickr" }, value: @start_date, placeholder: "dd/mm/yyyy" %>
              To: <%= f.text_field :end_date, class: "end_date", data: { behavior: "flatpickr" }, value: @end_date, placeholder: "dd/mm/yyyy" %>
        <br>
        <br>
        <h4>Total beers: <span id="total_price"></span></h4>
        <br>
        <%= f.submit "Book Now", class: "btn-solid"%>
        <% end%>
        <% else %>
        <div class="instrument-details">
          <h4>Description:</h4>
          <p><%= @instrument.description %></p>
        </div>
        <% end%>
        <br>
          <%= link_to "Back to search results", instruments_path %>
        </div>
        </div>

      </div>










    </div>

  </div>

</div>
<script>
  let myInput = document.querySelector("#new_booking");
  myInput.addEventListener("change", (event) => {
    const currentTarget = event.currentTarget;
    const start = document.querySelector("#booking_start_date");
    const end = document.querySelector("#booking_end_date");
    const oneDay = 24 * 60 * 60 * 1000;
    const firstDate = new Date(start.value);
    const secondDate = new Date(end.value);
    const diffDays = Math.round(Math.abs((firstDate - secondDate) / oneDay));
    if (diffDays>0) {
      document.querySelector("#total_price").innerHTML = (diffDays*5) +" 🍺";
    };

  });

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AirbnbClone</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <!-- google fonts -->
  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+TC:wght@300;400;500;700;900&display=swap" rel="stylesheet">

  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
</head>

<body>
  <%= render 'shared/navbar' %>
  <%= render 'shared/flashes' %>

  <div class="wrapper">

  <%= yield %>




</div>
<div class="push"></div>
  <%= render 'shared/footer' %>
</body>
</html>

app/views/pages/dashboard.html.erb
<h1 class="dashboard-welcome">Welcome <%= current_user.username.capitalize %></h1>
<hr>

<div class="wrapper-dashboard">
  <div class="row d-flex justify-content row-fix">
    <div class="col-md-auto your-bookings">
      <h2>Your bookings:</h2>
      <ul class="list-unstyled">
        <% @bookings.each do |booking| %>
          <% if booking.status == "Pending validation" %>
            <li class="dashboard">
              <div class='product-body card-product'>
                <% if booking.instrument.photo.attached? %>
                  <%= link_to (cl_image_tag booking.instrument.photo.key, height: 320, width: 320, crop: :fill, class: 'instrument-image'), instrument_path(booking.instrument) %>
                <% else %>
                  <%= link_to (cl_image_tag '/app/assets/images/guitar_dummy.jpg', height: 320, width: 320, crop: :fill, class: 'instrument-image'), instrument_path(booking.instrument) %>
                <% end %>
                <div class="card-product-infos row d-flex justify-content-between">
                  <div class="col-md-auto">
                    <h2><%= booking.instrument.name.titleize %></h2>
                    <div class="cancel-booking col-md-auto">
                        <%= link_to "Cancel Booking", booking_path(booking), method: :delete, data: { confirm: "Are you sure you want to delete"}, class: "btn btn-solid" %>
                    </div>
                  </div>
                  <div class="col-md-auto right-part">
                    <p><strong>From:</strong><%= booking.start_date %></p>
                    <p><strong>To:</strong><%= booking.end_date %></p>
                    <p><strong>Total price: </strong><%= (booking.end_date-booking.start_date).to_i*5 %> 🍺</p>
                    <p>Waiting for confirmation</p>
                  </div>
                </div>
              </div>
            </li>
          <% end %>
          <% if booking.status == "Confirmed" %>
            <li class="dashboard">
              <div class='product-body card-product'>
                <% if booking.instrument.photo.attached? %>
                  <%= link_to (cl_image_tag booking.instrument.photo.key, height: 320, width: 320, crop: :fill, class: 'instrument-image'), instrument_path(booking.instrument) %>
                <% else %>
                  <%= link_to (cl_image_tag '/app/assets/images/guitar_dummy.jpg', height: 320, width: 320, crop: :fill, class: 'instrument-image'), instrument_path(booking.instrument) %>
                <% end %>
                <div class="card-product-infos row d-flex justify-content-between">
                  <div class="col-md-auto">
                    <h2><%= booking.instrument.name.titleize %></h2>
                  </div>
                  <div class="col-md-auto right-part">
                    <p><strong>From:</strong><%= booking.start_date %></p>
                    <p><strong>To:</strong><%= booking.end_date %></p>
                    <p><strong>Total price: </strong><%= (booking.end_date-booking.start_date).to_i*5 %> 🍺</p>
                    <p><strong>Your booking is confirmed !</strong></p>
                  </div>
                </div>
              </div>
            </li>
          <% end %>
          <% if booking.status == "Canceled" %>
            <li class="dashboard">
              <div class='product-body card-product'>
                <% if booking.instrument.photo.attached? %>
                  <%= link_to (cl_image_tag booking.instrument.photo.key, height: 320, width: 320, crop: :fill, class: 'instrument-image'), instrument_path(booking.instrument) %>
                <% else %>
                  <%= link_to (cl_image_tag '/app/assets/images/guitar_dummy.jpg', height: 320, width: 320, crop: :fill, class: 'instrument-image'), instrument_path(booking.instrument) %>
                <% end %>
                <div class="card-product-infos row d-flex justify-content-between">
                  <div class="col-md-auto">
                    <h2><%= booking.instrument.name.titleize %></h2>
                  </div>
                  <div class="col-md-auto right-part">
                    <p><strong>From:</strong><%= booking.start_date %></p>
                    <p><strong>To:</strong><%= booking.end_date %></p>
                    <p><strong>Total price: </strong><%= (booking.end_date-booking.start_date).to_i*5 %> 🍺</p>
                    <p><strong><%= booking.instrument.user.username.titleize %> canceled your booking</strong></p>
                  </div>
                </div>
              </div>
            </li>
          <% end %>
        <% end %>
      </ul>
    </div>
    <div class="border">
    </div>
    <div class="col-md-auto booking-instruments">
      <h2>Bookings of your instruments:</h2>
      <ul class="list-unstyled">
        <% @instruments.each do |instrument| %>
          <% instrument.bookings.each do |booking| %>
              <li class="dashboard">
                <div class='product-body card-product'>
                  <% if booking.instrument.photo.attached? %>
                    <%= link_to (cl_image_tag booking.instrument.photo.key, height: 320, width: 320, crop: :fill, class: 'instrument-image'), instrument_path(booking.instrument) %>
                  <% else %>
                    <%= link_to instrument_path(instrument) do %>
                      <%= image_tag '/app/assets/images/guitar_dummy.jpg', class: 'instrument-image' %>
                    <% end %>
                  <% end %>
                  <div class="card-product-infos row d-flex justify-content-between">
                    <div class="col-md-auto">
                      <% if booking.status == "Pending validation" %>
                        <h5><%= booking.user.username.titleize %> wants to rent your <%= booking.instrument.name %></h5>
                        <div class="accept-buttons row d-flex justify-content-between">
                          <div class="accept col-md-auto">
                            <%= link_to "Accept ", booking_path(id: booking.id, booking: {status: "Confirmed"}), method: :patch, class: "btn btn-solid" %>
                          </div>
                          <div class="decline col-md-auto">
                            <%= link_to "Decline", booking_path(id: booking.id, booking: {status: "Canceled"}), method: :patch, class: "btn btn-ghost" %>
                          </div>
                        </div>
                      <% elsif booking.status == "Confirmed" %>
                        <h5>✔ Confirmed booking of <%= booking.user.username %></h5>
                        <div class="accept-buttons row d-flex justify-content-between">
                          <div class="accept col-md-auto">
                          </div>
                          <div class="decline col-md-auto">
                          </div>
                        </div>
                      <% elsif booking.status == "Canceled" %>
                        <h5>❌ You canceled booking of <%= booking.user.username %></h5>
                        <div class="accept-buttons row d-flex justify-content-between">
                          <div class="accept col-md-auto">
                          </div>
                          <div class="decline col-md-auto">
                          </div>
                        </div>
                      <% end %>
                    </div>
                    <div class="col-md-auto right-part">
                      <p><strong>From:</strong><%= booking.start_date %></p>
                      <p><strong>To:</strong><%= booking.end_date %></p>
                      <p><strong>Total price: </strong><%= (booking.end_date-booking.start_date).to_i*5 %> 🍺</p>
                    </div>
                  </div>
                </div>
              </li>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
  <div class="banner">
  <div class="picture">
    <div class="topic">
      <h1>Rent instruments with 🍺</h1>
    </div>
      <%= render 'shared/search' %>
  </div>
</div>

<div class="container home-welcome-text">
<h2>Instruments of the week:</h2>
  <div class="row d-flex justify-content-start">

    <% instrument_shuffle = @instruments.shuffle[0..2] %>
    <% instrument_shuffle.each do |instrument| %>

      <div class="card-trip col-md-auto">
        <% if instrument.photo.attached? %>
          <%= link_to (cl_image_tag instrument.photo.key, height: 320, width: 320, crop: :fill, class: 'instrument-image'), instrument_path(instrument) %>
        <% else %>
          <%= link_to instrument_path(instrument) do %>
            <%= image_tag '/app/assets/images/instruments/guitar_dummy.jpg', class: 'instrument-image' %>
          <% end %>
        <% end %>
        <div class="card-trip-infos">
          <div>
            <h2><%= instrument.name.titleize %></h2><%= link_to "Details", instrument %>
            <p><%= instrument.category.titleize %></p>

          </div>
          <h2 class="card-trip-pricing">5 🍺</h2>
          <%= cl_image_tag instrument.user.photo.key, height: 100, width: 100, crop: :fill, class: 'card-trip-user avatar-bordered'  %>
        </div>
      </div>
    <% end %>

  </div>

</div>

app/views/shared/_flashes.html.erb
<% if notice %>
    <div class="alert alert-info alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= notice %>
    </div>
  <% end %>
  <% if alert %>
    <div class="alert alert-warning alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= alert %>
    </div>
  <% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Rent instruments with 🍺
  </div>
</div>

app/views/shared/_navbar.html.erb
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "Goldtop-Guitar-icon.png", size: '50x50', class: 'header-iamge' %>
    <% end %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <% if user_signed_in? %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "List Instrument", new_instrument_path, class: "btn btn-ghost" %>
        </li>
        <li class="nav-item dropdown">
          <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      </ul>
    </div>
    <% else %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
        </li>
      </ul>
    <% end %>
    </div>
  </div>

app/views/shared/_search.html.erb
<%= form_tag instruments_path, class: "searchbar row justify-content-md-center", method: :get do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control col-md-auto input-field",
    placeholder: "Find an instrument"
  %>
  <%= submit_tag "Search", class: "btn-solid col-md-auto" %>
<% end %>